name: uuid
version: 4.2.0
description: >
  RFC4122 (v1, v4, v5, v6, v7, v8) UUID Generator and Parser for Dart
documentation: https://daegalus.github.io/dart-uuid/index.html
repository: https://github.com/Daegalus/dart-uuid
environment:
  sdk: ">=2.14.0 <4.0.0"
dependencies:
  crypto: ^3.0.0
  sprintf: ^7.0.0
  meta: ^1.11.0
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
funding:
  - https://ko-fi.com/yulian
  - https://paypal.me/yuliank
  - https://cash.app/$yulian
  - https://venmo.com/yuliank
topics:
  - uuid
  - identifier
  - id