name: uuid
version: 0.2.0
description: >
  RFC4122(v1,v4,v5) UUID Generator and Parser.
author: Yulian Kuncheff <yulian@kuncheff.com>
homepage: https://github.com/Daegalus/dart-uuid
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  crypto: ">=0.9.0 < 0.10.0"
  unittest: ">=0.9.0 < 0.10.0"
  cipher: ">=0.3.0"
