name: uuid
version: 0.4.0
description: >
  RFC4122(v1,v4,v5) UUID Generator and Parser.
author: Yulian Kuncheff <yulian@kuncheff.com>
homepage: https://github.com/Daegalus/dart-uuid
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  crypto: ">=0.9.0 <0.10.0"
  cipher: ">=0.7.0 <0.8.0"
dev_dependencies:
  unittest: any
